### ISSUE TITLE
Replication origin "pgcopydb" already exists at LSN 1/44002278

### ISSUE THREAD

**Issue by dbvan** [dimitri/pgcopydb#360]
I tried to copy from AWS RDS Postgresql to Google Cloud SQL for Postgresql with version postgresql 11.
During the setup of replication, I executed the command to create a replication origin with the name "pgcopydb". However, the process failed, and I received the following error message:
`12:30:03 27 ERROR  ld_stream.c:2352 Replication origin "pgcopydb" already exists at LSN 1/44002278`

I follow step:
1. docker run --rm -it ghcr.io/dimitri/pgcopydb:latest bash
2.  pgcopydb version
```
12:45:21 9 INFO   Running pgcopydb version 0.12.5.gd1cceab from "/usr/local/bin/pgcopydb"
pgcopydb version 0.12.5.gd1cceab
compiled with PostgreSQL 13.11 (Debian 13.11-0+deb11u1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
compatible with Postgres 10, 11, 12, 13, 14, and 15
```
3. Command copy:
```
pgcopydb clone --table-jobs 4 --index-jobs 4 --no-owner --no-acl --follow  \
--plugin wal2json --create-slot --slot-name pgcopydbtest2 \
--no-role-passwords --drop-if-exists \
--debug \
--source "port=5432 host=rds2cloudsql.xxx.ap-southeast-1.rds.amazonaws.com dbname=test2 user=postgres password=xxxx" \
--target "port=5432 host=34.xx.xx.3 dbname=test user=postgres password=xxxx"
```
```
Log debug from command pgcopydb:
12:30:03 27 INFO   Running pgcopydb version 0.12.5.gd1cceab from "/usr/local/bin/pgcopydb"
12:30:03 27 DEBUG  copydb.c:525              Change Data Capture data is managed at "/var/lib/postgres/.local/share/pgcopydb"
12:30:03 27 INFO   cli_common.c:1186         [SOURCE] Copying database from "postgres://postgres@rds2cloudsql.xxxx.ap-southeast-1.rds.amazonaws.com:5432/test2"
12:30:03 27 INFO   cli_common.c:1187         [TARGET] Copying database into "postgres://postgres@34.xx.xx.3:5432/test"
12:30:03 27 DEBUG  cli_common.c:1191         Using pg_dump for Postgres "13.11" at "/usr/bin/pg_dump"
12:30:03 27 DEBUG  cli_common.c:1195         Using pg_restore for Postgres "13.11" at "/usr/bin/pg_restore"
12:30:03 27 DEBUG  copydb.c:525              Change Data Capture data is managed at "/var/lib/postgres/.local/share/pgcopydb"
12:30:03 27 NOTICE copydb.c:85               Using work dir "/tmp/pgcopydb"
12:30:03 27 NOTICE copydb.c:357              Work directory "/tmp/pgcopydb" already exists
12:30:03 27 NOTICE copydb.c:117              Schema dump has not been done yet, just continue
12:30:03 27 DEBUG  lock_utils.c:138          Created semaphore 7 (cleanup with ipcrm -s)
12:30:03 27 DEBUG  lock_utils.c:138          Created semaphore 8 (cleanup with ipcrm -s)
12:30:03 27 DEBUG  queue_utils.c:45          Created message vacuum queue 6 (cleanup with `ipcrm -q 6`)
12:30:03 27 DEBUG  queue_utils.c:45          Created message create index queue 7 (cleanup with `ipcrm -q 7`)
12:30:03 27 DEBUG  queue_utils.c:45          Created message transform queue 8 (cleanup with `ipcrm -q 8`)
12:30:03 27 SQL    pgsql.c:508               Connecting to [source] "postgres://postgres@rds2cloudsql.xxxx.ap-southeast-1.rds.amazonaws.com:5432/test2?replication=database"
12:30:03 27 INFO   pgsql.c:3563              Created logical replication slot "pgcopydbtest2" with plugin "wal2json" at 2/B80000C8 and exported snapshot 0000000D-00000B8F-1
12:30:03 27 SQL    pgsql.c:508               Connecting to [source] "postgres://postgres@rds2cloudsql.xxxx.ap-southeast-1.rds.amazonaws.com:5432/test2"
12:30:03 27 SQL    pgsql.c:1494              [SOURCE] BEGIN;
12:30:03 27 INFO   ld_stream.c:2419          create schema if not exists pgcopydb
12:30:03 27 SQL    pgsql.c:1494              [SOURCE] create schema if not exists pgcopydb;
12:30:03 27 INFO   ld_stream.c:2419          drop table if exists pgcopydb.sentinel
12:30:03 27 SQL    pgsql.c:1494              [SOURCE] drop table if exists pgcopydb.sentinel;
12:30:03 27 WARN   pgsql.c:840               NOTICE:  table "sentinel" does not exist, skipping
12:30:03 27 INFO   ld_stream.c:2419          create table pgcopydb.sentinel(startpos pg_lsn, endpos pg_lsn, apply bool,  write_lsn pg_lsn, flush_lsn pg_lsn, replay_lsn pg_lsn)
12:30:03 27 SQL    pgsql.c:1494              [SOURCE] create table pgcopydb.sentinel(startpos pg_lsn, endpos pg_lsn, apply bool,  write_lsn pg_lsn, flush_lsn pg_lsn, replay_lsn pg_lsn);
12:30:03 27 SQL    pgsql.c:1494              [SOURCE] insert into pgcopydb.sentinel (startpos, endpos, apply, write_lsn, flush_lsn, replay_lsn) values($1, $2, $3, '0/0', '0/0', '0/0');
12:30:03 27 SQL    pgsql.c:1498              '2/B80000C8', '0/0', 'false'
12:30:03 27 SQL    pgsql.c:1494              [SOURCE] create unique index on pgcopydb.sentinel((1));
12:30:03 27 SQL    pgsql.c:1494              [SOURCE] COMMIT;
12:30:03 27 SQL    pgsql.c:418               Disconnecting from [source] "postgres://postgres@rds2cloudsql.xxxx.ap-southeast-1.rds.amazonaws.com:5432/test2"
12:30:03 27 SQL    pgsql.c:508               Connecting to [target] "postgres://postgres@34.x.x.3:5432/test"
12:30:03 27 SQL    pgsql.c:1494              [TARGET] BEGIN;
12:30:03 27 SQL    pgsql.c:1494              [TARGET] select pg_replication_origin_oid($1);
12:30:03 27 SQL    pgsql.c:1498              'pgcopydb'
12:30:03 27 SQL    pgsql.c:1494              [TARGET] select pg_replication_origin_progress($1, $2);
12:30:03 27 SQL    pgsql.c:1498              'pgcopydb', 't'
12:30:03 27 ERROR  ld_stream.c:2352          Replication origin "pgcopydb" already exists at LSN 1/44002278
12:30:03 27 SQL    pgsql.c:418               Disconnecting from [target] "postgres://postgres@34.x.x.3:5432/test"
12:30:03 27 DEBUG  queue_utils.c:60          iprm -q 8 (transform)
12:30:03 27 DEBUG  queue_utils.c:60          iprm -q 7 (create index)
12:30:03 27 DEBUG  queue_utils.c:60          iprm -q 6 (vacuum)
```
Please let me know if any further information is needed to investigate and resolve this issue. Your prompt attention to this matter is greatly appreciated.

**Comment by dimitri** [comment]
Hi @dbvan ; it looks like you did try the `pgcopydb clone --follow` several times and the replication setup was already done for you. Consider cleaning-up the replication setup between different attempts if you don't want to try and resume from the previous try, which requires holding to a snapshot with a separate `pgcopydb snapshot` command in the general case. See command `pgcopydb stream cleanup` documented at https://pgcopydb.readthedocs.io/en/latest/ref/pgcopydb_stream.html#pgcopydb-stream-cleanup.

Consider opening this issue again with more information if needed.

**Comment by dbvan** [comment]
Hi @dimitri ,
I tried command `pgcopydb stream cleanup` but facing error `Segmentation fault`:

Core dump file analysis:
```
Core was generated by `/usr/local/bin/pgcopydb stream cleanup --source port=5432 host=database-1.copdc'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005557d9efdac8 in strlcpy ()
(gdb) bt
#0  0x00005557d9efdac8 in strlcpy ()
#1  0x00005557d9ebb044 in cli_stream_getopts (argc=6, argv=0x7ffe511ec078) at cli_stream.c:248
#2  0x00005557d9ef533a in commandline_run (command=command@entry=0x7ffe511eba00, argc=6, argc@entry=8, argv=0x7ffe511ec078, argv@entry=0x7ffe511ec068)
    at /usr/src/pgcopydb/src/bin/pgcopydb/../lib/subcommands.c/commandline.c:59
#3  0x00005557d9eb1da2 in main (argc=8, argv=0x7ffe511ec068) at main.c:167
```

**Comment by dimitri** [comment]
The Seg Fault should now be fixed, thanks for reporting.
