### ISSUE TITLE
pgcopydb stream sentinel get segmentation fault

### ISSUE THREAD

**Issue by marcocitus** [dimitri/pgcopydb#377]
The following command gave a segmentation fault:
```
$ pgcopydb stream sentinel get --source "host=localhost port=1400"                                                                        
12:57:24 31823 INFO   Running pgcopydb version 0.11.31.gc3ce5f4 from "/home/marco/pgsql/15/bin/pgcopydb"
Segmentation fault (core dumped)
```

Strack trace from GDB:
```
Program received signal SIGSEGV, Segmentation fault.
0x00005555555a9203 in strlcpy (dst=<optimized out>, src=0x7fffffffea54 "host=localhost port=1400", siz=siz@entry=1024) at strlcpy.c:56
56                              if ((*d++ = *s++) == '\0')
(gdb) bt
#0  0x00005555555a9203 in strlcpy (dst=<optimized out>, src=0x7fffffffea54 "host=localhost port=1400", siz=siz@entry=1024) at strlcpy.c:56
#1  0x00005555555644af in cli_sentinel_getopts (argc=3, argv=0x7fffffffe780) at cli_sentinel.c:175
#2  0x00005555555a13cd in commandline_run (command=0x5555555df120 <sentinel_get_command>, argc=argc@entry=3, argv=argv@entry=0x7fffffffe780)
    at /home/marco/pgcopydb/src/bin/pgcopydb/../lib/subcommands.c/commandline.c:59
#3  0x00005555555a14cd in commandline_run (command=0x5555555def20 <sentinel_commands>, argc=3, argc@entry=4, argv=0x7fffffffe780, argv@entry=0x7fffffffe778)
    at /home/marco/pgcopydb/src/bin/pgcopydb/../lib/subcommands.c/commandline.c:94
#4  0x00005555555a14cd in commandline_run (command=0x5555555df660 <stream_commands>, argc=4, argc@entry=5, argv=0x7fffffffe778, argv@entry=0x7fffffffe770)
    at /home/marco/pgcopydb/src/bin/pgcopydb/../lib/subcommands.c/commandline.c:94
#5  0x00005555555a14cd in commandline_run (command=command@entry=0x7fffffffe1f0, argc=5, argc@entry=6, argv=0x7fffffffe770, argv@entry=0x7fffffffe768)
    at /home/marco/pgcopydb/src/bin/pgcopydb/../lib/subcommands.c/commandline.c:94
#6  0x0000555555584e17 in main (argc=6, argv=0x7fffffffe768) at main.c:167
```

**Comment by dimitri** [comment]
Looks a lot like https://github.com/dimitri/pgcopydb/pull/371 actually. Oops.
