### ISSUE TITLE
pgcopydb list progress segmentation fault during pgcopydb clone

### ISSUE THREAD

**Issue by marcocitus** [dimitri/pgcopydb#409]
During part of the `pgcopydb clone`, I consistently see a segmentation fault when running `pgcopydb list progress`:
```
pgcopydb list progress --dir /tmp/pgcopydb_66 --json 
12:44:32 25132 INFO   Running pgcopydb version 0.11.31.gc3ce5f4 from "/home/marco/pgsql/15/bin/pgcopydb"
12:44:32 25132 INFO   Schema dump for pre-data and post-data section have been done                                                                                                
12:44:32 25132 INFO   Pre-data schema has been restored on the target instance                                                                                                     
12:44:32 25132 INFO   All the sequences have been copied to the target instance                                                                                                    
12:44:32 25132 INFO   All the large objects have been copied to the target instance                                                                                                
Segmentation fault (core dumped)      
```
Stack trace:
```
#0  __strlen_evex () at ../sysdeps/x86_64/multiarch/strlen-evex.S:77
#1  0x00007f126146d603 in __GI___strdup (s=0x0) at ./string/strdup.c:41
#2  0x000055fdb3ebb0e2 in read_index_summary (summary=summary@entry=0x7ffdef27be00, filename=filename@entry=0x55fdb4df9d80 "/tmp/pgcopydb_66/run/240174") at summary.c:412
#3  0x000055fdb3eb2f2d in copydb_update_progress (copySpecs=copySpecs@entry=0x7ffdef27f0c0, progress=progress@entry=0x7ffdef27cf60) at progress.c:974
#4  0x000055fdb3e7ebae in cli_list_progress (argc=<optimized out>, argv=<optimized out>) at cli_list.c:1736
#5  0x000055fdb3ec00a2 in commandline_run (command=0x55fdb3efd1c0 <list_progress_command>, argc=0, argc@entry=6, argv=0x7ffdef390a28, argv@entry=0x7ffdef3909f8)
    at /home/marco/pgcopydb/src/bin/pgcopydb/../lib/subcommands.c/commandline.c:71
#6  0x000055fdb3ec0184 in commandline_run (command=0x55fdb3efd120 <list_commands>, argc=6, argc@entry=7, argv=0x7ffdef3909f8, argv@entry=0x7ffdef3909f0)
    at /home/marco/pgcopydb/src/bin/pgcopydb/../lib/subcommands.c/commandline.c:94
#7  0x000055fdb3ec0184 in commandline_run (command=command@entry=0x7ffdef390470, argc=7, argc@entry=8, argv=0x7ffdef3909f0, argv@entry=0x7ffdef3909e8)
    at /home/marco/pgcopydb/src/bin/pgcopydb/../lib/subcommands.c/commandline.c:94
#8  0x000055fdb3ea36cb in main (argc=8, argv=0x7ffdef3909e8) at main.c:167
```
Note that during other parts of the clone it works fine.

**Comment by dimitri** [comment]
Can you make sure you have https://github.com/dimitri/pgcopydb/pull/391 in your version of pgcopydb? I think we fixed that bug already and it seems you're running pgcopydb version 0.11.31.gc3ce5f4, which is 68 commits before the fix and 81 commits before the current main branch apparently...

**Comment by marcocitus** [comment]
it's fixed, sorry for the noise
