### ISSUE TITLE
[online] On setting endpos follow mode switches as replay => catchup => replay and gets stuck

### ISSUE THREAD

**Issue by shubhamdhama** [dimitri/pgcopydb#500]
Here is the backtrace of stuck transform process.
```
#0  0x00007f13b6091f7a in __GI___select (nfds=nfds@entry=13, readfds=readfds@entry=0x7ffe6149c3d0, writefds=writefds@entry=0x0, exceptfds=exceptfds@entry=0x0, timeout=timeout@entry=0x7ffe6149c3c0) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x0000555c90c8f2c7 in read_from_stream (stream=0x555c91c7a5e0, context=context@entry=0x7ffe6149e4b0) at file_utils.c:445
#2  0x0000555c90ca1894 in stream_transform_stream (specs=specs@entry=0x7ffe6149ea20) at ld_transform.c:102
#3  0x0000555c90ca2a1a in follow_start_transform (specs=0x7ffe6149ea20) at follow.c:667
#4  0x0000555c90ca21fd in follow_start_subprocess (specs=specs@entry=0x7ffe6149ea20, subprocess=subprocess@entry=0x7ffe615a7760) at follow.c:776
#5  0x0000555c90ca2bc3 in follow_start_subprocess (specs=0x7ffe6149ea20, subprocess=0x7ffe615a7760) at follow.c:761
#6  0x0000555c90ca33eb in followDB (copySpecs=<optimized out>, streamSpecs=0x7ffe6149ea20) at follow.c:542
#7  followDB (copySpecs=<optimized out>, streamSpecs=0x7ffe6149ea20) at follow.c:476
#8  0x0000555c90ca3672 in follow_main_loop (copySpecs=copySpecs@entry=0x7ffe615aa1c0, streamSpecs=streamSpecs@entry=0x7ffe6149ea20) at follow.c:286
#9  0x0000555c90c814f6 in start_follow_process (pid=<synthetic pointer>, streamSpecs=0x7ffe6149ea20, copySpecs=0x7ffe615aa1c0) at cli_clone_follow.c:677
#10 clone_and_follow (copySpecs=0x7ffe615aa1c0) at cli_clone_follow.c:269
#11 cli_clone (argc=<optimized out>, argv=<optimized out>) at cli_clone_follow.c:142
#12 0x0000555c90ccf10c in commandline_run (command=<optimized out>, argc=0, argv=0x7ffe616bdc10) at /home/shdhama/pg/pgcopydb/src/bin/pgcopydb/../lib/subcommands.c/commandline.c:71
#13 0x0000555c90c808f6 in main (argc=15, argv=0x7ffe616bdb98) at main.c:167
```

I'm able to reproduce this without any activity on source.
Here are complete logs:
[date-23-10-16--time-15-18-14.log](https://github.com/dimitri/pgcopydb/files/12919180/date-23-10-16--time-15-18-14.log)

**Comment by arajkumar** [comment]
@shubhamdhama I've also this behavior and added some context here: https://github.com/dimitri/pgcopydb/issues/427#issuecomment-1757910281

**Comment by shubhamdhama** [comment]
@dimitri, @arajkumar let me clarify. I'm talking about two issues here, first is transform process getting blocked. But the more concerning issue here is transition from catchup => replay (and on meeting endpos again transition to) => catchup => replay (blocked).

**Comment by dimitri** [comment]
See also #521
